"""init database

Revision ID: 03d2d9cdfeaa
Revises: 
Create Date: 2017-07-24 12:46:51.731189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d2d9cdfeaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', drive.model.meta.types.EmailAddress(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DRIVER', 'MANAGER', 'NORMAL', name='text', metadata=MetaData(bind=None)), nullable=True),
    sa.Column('last_credential_change_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', 'deleted_at', name=op.f('uq_users_email'))
    )
    op.create_table('account',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.Unicode(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_account_user_id_users'), onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account'))
    )
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_table('account')
    op.drop_table('users')
    # ### end Alembic commands ###
