"""init database

Revision ID: 1baebe77db65
Revises: f0f5a986e4be
Create Date: 2017-07-18 18:08:55.426137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1baebe77db65'
down_revision = 'f0f5a986e4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('group_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(op.f('fk_driver_group_id_driver'), 'driver', 'driver', ['group_id'], ['id'], onupdate='cascade', ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_driver_group_id_driver'), 'driver', type_='foreignkey')
    op.drop_column('driver', 'group_id')
    # ### end Alembic commands ###
