"""init database

Revision ID: cbb1d2935789
Revises: 
Create Date: 2017-07-18 16:48:35.010203

"""
from alembic import op
import sqlalchemy as sa
import drive
from sqlalchemy import MetaData

# revision identifiers, used by Alembic.
revision = 'cbb1d2935789'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy'))
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', drive.model.meta.types.EmailAddress(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DRIVER', 'MANAGER', name='text', metadata=MetaData(bind=None)), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('password', drive.utils.encrypt.EncryptPassword(), nullable=True),
    sa.Column('_phone_number', sa.Unicode(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('id', 'email', name=op.f('uq_user_id'))
    )
    op.create_table('driver',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_authorized', sa.Boolean(), nullable=False),
    sa.Column('cdl_state', sa.Text(), nullable=True),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('_office_phone_number', sa.Unicode(length=20), nullable=True),
    sa.Column('license_number', sa.Text(), nullable=True),
    sa.Column('usdot', sa.Text(), nullable=True),
    sa.Column('carrier_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_driver_user_id_user'), onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver'))
    )
    op.create_table('driver_policy',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.id'], name=op.f('fk_driver_policy_driver_id_driver'), onupdate='cascade', ondelete='cascade'),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], name=op.f('fk_driver_policy_policy_id_policy'), onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_policy'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_policy')
    op.drop_table('driver')
    op.drop_table('user')
    op.drop_table('policy')
    # ### end Alembic commands ###
